import type { EditorState } from './editor.types';

export const initialEditorState: EditorState = {
  information: {
    username: null,
    fullname: null,
    avatar_url: null,
    code: null,
    token: null,
    locationid: null,
    lat: null,
    lon: null,
    point_end: null,
    point_start: null,
    class_01: null,
    class_02: null,
    class_03: null,
    class_04: null,
    class_05: null,
    marker_01: null,
    marker_02: null,
    marker_03: null,
    marker_04: null,
    marker_05: null,
    marker_06: null,
    marker_07: null,
    marker_08: null,
    marker_09: null,
    marker_10: null,
    marker_11: null,
    marker_12: null,
    travel_01: null,
    travel_02: null,
    travel_03: null,
    travel_04: null,
    travel_05: null,
    travel_06: null,
    travel_07: null,
    travel_08: null,
    travel_09: null,
    travel_10: null,
  },
  sidebar: {
    open: false,
  },
  navbar_x: {
    location_search: null,
    detail: false,
    brand: 'review',
    image: false,
    option: null,
    headerXy: false,
    introducerX: false,
    Xreview: 'overview',
    save: 'list',
    back: false,
    dynamic: false,
    activeX: { type: null },
    active: { type: null, value: null },
    hover: { type: null, value: null },
    project: false,
    group: false,
    chat: false,
    open_project: false,
    open_group: false,
    open_chat: false,
    open_index_project: false,
    index_project: null,
    index_project_prev: null,
    index_group: null,
    index_group_prev: null,
    index_chat: null,
    list: [
      {
        type: 'project',
        items: [
          'Học tập',
          'Giải trí',
          'Chơi game',
          'Ôn thi',
          'Báo cáo',
          'May rủi',
          'Sức khỏe',
          'Tâm lý',
          'Giáo dục',
          'Kinh tế',
          'Xã hội',
        ],
      },
      {
        type: 'group',
        items: [
          'Xem phim',
          'Đọc truyện',
          'Bắn súng',
          'Thi đấu',
          'Đá bóng',
          'Cờ vua',
        ],
      },
      {
        type: 'chat',
        items: [
          'Python',
          'JavaScript',
          'Dart',
          'Java',
          'C#',
          'Golang',
          'Rust',
          'C++',
          'Ruby',
          'Php',
        ],
      },
    ],
  },
  util: {
    active: false,
    loading: false,
    hover: false,
    error: '',
    index: null,
    open: false,
    lockForgot: false,
    lockRegister: false,
    lockReset: false,
  },
  dropdown: {
    logout: false,
  },
  tooltip: {
    logo: false,
    add: false,
    search: false,
    image: false,
    spackle: false,
    logout: false,
  },
  modal: {
    profile: false,
    update: false,
    person: false,
    setup: false,
    help: false,
    logout: false,
    project: false,
  },
  position: {
    open_project: false,
    project: {
      top: null,
      left: null,
    },
  },
};
